# Generated by Django 5.1.4 on 2024-12-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_employee_location_remove_employee_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('employee', 'Employee'), ('warehouse_manager', 'Warehouse_Manager')], max_length=20),
        ),
    ]
