graph LR
    A[Jireh-dashboard] --> B[.next/]
    A --> C[node_modules/]
    A --> D[public/]
    A --> E[src/]
    E --> F[app/]
    F --> G[auth/]
    G --> H[forgot-password/]
    H --> H1[page.tsx]
    G --> I[login/]
    I --> I1[page.tsx]
    G --> J[register/]
    J --> J1[page.tsx]
    G --> K[reset-password/]
    K --> K1[page.tsx]
    G --> L[subscription/]
    L --> L1[page.tsx]
    G --> M[layout.tsx]
    F --> N[dashboard/]
    N --> O[admin/]
    O --> P[categories/]
    P --> P1[page.tsx]
    O --> Q[employees/]
    Q --> Q1[page.tsx]
    O --> R[items/]
    R --> R1[page.tsx]
    O --> S[locations/]
    S --> S1[page.tsx]
    O --> T[orders/]
    T --> T1[page.tsx]
    O --> U[profile/]
    U --> U1[page.tsx]
    O --> V[users/]
    V --> V1[page.tsx]
    O --> W[layout.tsx]
    O --> X[page.tsx]
    N --> Y[sadmin/]
    Y --> Z[stores/]
    Z --> AA[categories/]
    AA --> AA1[page.tsx]
    Z --> AB[employees/]
    AB --> AB1[page.tsx]
    Z --> AC[items/]
    AC --> AC1[page.tsx]
    Z --> AD[locations/]
    AD --> AD1[page.tsx]
    Z --> AE[orders/]
    AE --> AE1[page.tsx]
    Z --> AF[users/]
    AF --> AF1[page.tsx]
    Z --> AG[page.tsx]
    Y --> AH[subscriptions/]
    AH --> AH1[page.tsx]
    Y --> AI[page.tsx]
    N --> AJ[sales/]
    AJ --> AK[order/]
    AK --> AK1[page.tsx]
    AJ --> AL[orders/]
    AL --> AL1[page.tsx]
    AJ --> AM[profile/]
    AM --> AM1[page.tsx]
    AJ --> AN[layout.tsx]
    AJ --> AO[page.tsx]
    N --> AP[warehouse/]
    AP --> AQ[items/]
    AQ --> AQ1[page.tsx]
    AP --> AR[orders/]
    AR --> AR1[page.tsx]
    AP --> AS[profile/]
    AS --> AS1[page.tsx]
    AP --> AT[layout.tsx]
    AP --> AU[page.tsx]
    F --> AV[fonts/]
    F --> AW[legal/]