# Generated by Django 5.1.4 on 2024-12-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('full_time', 'FULL_TIME'), ('part', 'Part'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=20),
        ),
    ]
